version = 1

exclude_patterns = [
  "system/**",
  "application/libraries/**",
  "application/views/**",
  "user_guide/**",
  "**/vendor/**"
]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true
